#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#nitrogen --restore &
gsettings set org.gnome.desktop.interface gtk-theme Matcha-dark-sea &
#gsettings set org.gnome.desktop.interface color-scheme prefer-dark
polybar -q Main &
dunst &
picom &
nm-applet &
variety &
deluge &
numlockx &
xfce4-clipman &
/usr/lib/xfce-polkit/xfce-polkit &
whatsapp-for-linux &
export GTK2_RC_FILES="$HOME/.gtkrc-2.0" &

#bspc monitor -d "Home" "File" "WWW" "MP4" "TXT" "Term" "Torrent" "CBZ" 
#bspc monitor -d "" "" "󰊯" "" "" "" "" "" 
bspc monitor -d "󰋜" "" "" "" "󱃖" "" "" "󰂺"

bspc config border_width         2
bspc config window_gap          6

bspc config normal_border_color "#484848"
bspc config focused_border_color "#EC7875"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Lxappearance state=floating
bspc rule -a Gcolor3 state=floating
bspc rule -a Viewnior state=floating
bspc rule -a Whatsapp-for-linux state=floating
bspc rule -a discord state=floating
bspc rule -a feh state=floating

#Desktop Rules
bspc rule -a Thunar desktop='^2'
bspc rule -a Alacritty desktop='^6'
bspc rule -a Vivaldi-stable desktop='^3'
bspc rule -a Brave-Browser desktop='^3'
bspc rule -a firefox desktop='^1'
bspc rule -a thunderbird desktop='^1'
bspc rule -a Geany desktop='^5'
bspc rule -a obsidian desktop='^5'
bspc rule -a vlc desktop='^4'
bspc rule -a Google-chrome desktop='^3'
bspc rule -a Deluge desktop=^7
bspc rule -a Whatsapp-for-linux desktop=^8
